### ISSUE TITLE
Backup settings - feature request

### ISSUE THREAD

**Issue by guaiamum** [pock/pock#277]
Hi, first of all really cool project!

**User story (base on a true tale 😆)**
I'm seeing my self on the verge to **change devices** 💻, but I'd like **Backup/Save** 💾 settings to a JSON file or something alike, _so I can_ **import it** ⬇️ on the fresh install on my new Macbook Pro!

- [ ] Backup Settings to file
- [ ] Import them in a fresh install (if not fresh, ask if settings should be overriden)

I'd love to help and perhaps implement this feature, but my knowledge in Swift and basically none. If you think this is an easy and simple feature that you'd like to have on the project, you could link some fine courses so I can learn and perhaps contribute a bit to the project 😄 In the feature this could evolve to:
1. Auto-save
2. Save it to Google Drive or iCloud to a more seamless experience to the user

**Comment by lucask42** [comment]
Looks to me like Pock's settings are stored in the global settings.  If it were me I'd manually transfer if settings weren't yet portable.  Here's how I would do it.

0) install Pock on the new machine, make sure the version numbers match and the OS version numbers are similar

1) on the old machine's terminal run:
`defaults read -app Pock`

2) take a copy of the settings including the enclosing curly braces

3) convert any double-slashes to single slashes before moving on.  When writing settings to the new machine it will add a slash before every slash it sees in order to 'escape' it and we want to wind up with the same double-slash in the end.
For example, `"\\"never\\"";` becomes `"\"never\"";` 

4) on the new machine's terminal run
`defaults write -app Pock '`paste your settings here`'`

5) quit and restart Pock

**Comment by guaiamum** [comment]
Nice, thanks :) Maybe I'll make a script on it. Time machine took the job when I switched macs tho :)
