### ISSUE TITLE
Hold and Slide in Control Center widget

### ISSUE THREAD

**Issue by xiaochunjimmy** [pock/pock#280]
**Describe the feature you'd like to have in Pock**
When I just display a "volume down" or "volume up" icon on my touch bar control center widget, I hope I can touch and hold and then slide to volume up and down without finger leaving the touch bar.
Just as the system widget.

**Additional context**
Auto quit control center widget.
When I open the control center widget, it won't quit automatically. I hope it can quit automatically after seconds just like the system widget.

**Comment by k06a** [comment]
You can keep the System Widget. Just configure it to have 2 buttons: volume and brightness adjustments.
![image](https://user-images.githubusercontent.com/702124/70379589-13474900-1948-11ea-81a2-949ca3747fd5.png)

`Cmd+Shift+6`:
![image](https://user-images.githubusercontent.com/702124/70379634-8650bf80-1948-11ea-8cbf-b70fa06dcacf.png)

Does anyone know why it has 3 buttons instead of 2?

**Comment by pigigaldi** [comment]
Hi @k06a, the third button is for opening Pock if you close it using the left-most `cross` button.
It's just strange that it hasn't the proper icon showed 🤔

**Comment by xiaochunjimmy** [comment]
@k06a Thank you for your idea, perfect for me.

**Comment by k06a** [comment]
Problem was solved for me, Apple removed TouchBar in latest MacBooks 😁
