### ISSUE TITLE
Unable to drag items out from customization menu

### ISSUE THREAD

**Issue by archcorsair** [pock/pock#295]
**Describe the bug**
Mouse cursor does not "drop into" the touch bar to be able to drag items out

**How to reproduce**
```
1. Open Customization menu
2. Attempt to drag mouse into the touchbar
3. Observe mouse does not enter touchbar 
4. Cannot customize
```

**Expected behavior**
Should be able to remove items from touchbar by dragging them out

**Screenshots**
Unable to remove `esc`:
![image](https://user-images.githubusercontent.com/1036921/70120868-5640ae00-1622-11ea-95f8-6aa76eca27e1.png)

**Versions:**
 - macOS version: 10.15.1 (19B2106)
 - Pock version:  0.6.3

**Additional context**
Macbook Pro 16 inch with physical esc button

**Comment by joakimgrr** [comment]
I'm experiencing the same issue, with the same specs.

**Versions**:
macOS version: 10.15.1 (19B2106)
Pock version: 0.6.3

**Additional context**
Macbook Pro 16 inch with physical esc button

**Comment by archcorsair** [comment]
Not going to close this issue, but toggling it about 15 times made it work for me. It now works every single time after taking @joakimgrr's suggestion. Weird.

**Comment by L1cardo** [comment]
You can try toggling by hand physically on the Touch Bar, this will work.
As for mouse issue, it didn’t happen to me.
MacBook Pro 16 inch model

**Comment by pigigaldi** [comment]
I can't figure out if this issue is related to Pock or MBP16" with macOS 10.15.1
I'll keep this issue open since I still need some time to investigate this case.

**Comment by L1cardo** [comment]
MBP16'',  I can not drag mouse into Touch Bar either.

**Comment by EricKit** [comment]
For anyone else experiencing this, as a temporary workaround, you can drag your mouse down into the touch by dragging the icon you want to remove into the Touch Bar. 

For example, drag `esc` into the Touch Bar, release and your mouse will be invisible, but it is still there and on top of `esc`. Click again and drag `esc` out.

**Comment by DominikBucher12** [comment]
There is Fix for this.
 Put `NSApp.activate(ignoringOtherApps: true)` just before calling `NSApp.toggleTouchBarCustomizationPalette(_:)`  in `PKTouchBarController.swift`

The reason why this is happenng is that macOS probably requires the application to be frontmost when changing the touchBar items so it can focus actually to **YOUR** application's touchbar instead of **FRONTMOST** application Touchbar

I'd create MR, but the project doesn't compile on `Localization.Identifiers` missing, this is issue for someone else :) So when the project compiles, I am happy to create merge request... If someone won't do this for me @pigigaldi :)

**Comment by DominikBucher12** [comment]
On the other hand, few minutes: https://github.com/pigigaldi/Pock/pull/419
