### ISSUE TITLE
Control Centre brightness widget occasionally jumps back to slider UI. (press, NOT hold)

### ISSUE THREAD

**Issue by vincentneo** [pock/pock#302]
**Describe the bug**
Most of the time, using the brightness up or down control centre widget, would directly trigger the brightness differences, as per pre-touch bar MacBook Pros.

However, sometimes, at random, the slider UI pops up instead, when I press it (not press and hold)

**How to reproduce**
Steps to reproduce the behaviour:
1. Set control centre widget to only brightness down and up
2. Just a quick press to either brightness up or down, on the Touch Bar.

**Expected behaviour**
Should increase/decrease brightness immediately when clicked;
Should show slider UI only when press and hold.

**Crashlog**
No crash logs

**Versions:**
 - macOS version: [10.14.6]
 - Pock version:  [0.6.3]

**Comment by jhgunter** [comment]
This could be related: I've found that adjusting brightness via the slider does not change where Pock "remembers" the brightness to be for the regular adjustment buttons:

**Steps to reproduce**
1. Use the brightness down button to set brightness to the minimum setting (one square).
2. Long press the brightness widget to bring up the slider.
3. Using the slider, adjust brightness to around 50–75%.
4. Press the (x) icon to return to the normal Pock view.
5. Press the brightness up button.
6. The brightness should adjust to two squares (i.e., one above the value set in step **1**, ignoring the value set in step 3).

**Expected behavior**
Step 5 should increase the brightness one square up from its current value at the time the button is pressed.

**Versions**
* macOS 10.15.1
* Pock 0.6.3

If this is unrelated, just let me know and I'll open a new issue for it.

**Comment by Feanaaro** [comment]
I encounter the same issue from time to time.
Would it be possible to make the slider-on-long-press optional, with a toggle in the app preferences?

**Comment by fontvu** [comment]
Hi,

I also encountered this problem. At first, I thought there should be a feature of setting the hold threshold, but it seems like a bug after all.

Versions

- macOS 10.15.3
- Pock 0.7.2

**Comment by deveul** [comment]
Same here, also for volume, slider appears randomly even if I disabled it in pock preference.
