### ISSUE TITLE
Pock stops displaying on Touch Bar (but DOES NOT QUIT)

### ISSUE THREAD

**Issue by delfuego** [pock/pock#356]
At times I can't explain or reproduce, Pock stops displaying on the Touch Bar, which reverts back to the standard macOS Touch Bar. Pock itself is still running, and still visible in the menu bar — it just isn't displaying on the Touch Bar.

If I go to the Pock item in the menu bar, and I choose the "Customize..." option, and then immediately click "Done" from the Pock customization screen, then Pock is restored into the Touch Bar. (Note that this is NOT true if I choose the "Preferences..." menu option and dismiss it.)

In terms of reproduction, I honestly don't know what the triggering event is for this; it's been happening for the past 2-3 weeks to me, and I've tried to pay attention to see if I could deduce what was causing it. I can't figure it out. I don't have any meaningful entries in any system log I can find, no crash reports (because it isn't crashing!), nothing.

**Versions:**
 - macOS version: 10.15.3 (build 19D76)
 - Pock version:  0.7.2

**Comment by simonuvarov** [comment]
I installed the app for the first time and experienced the same issue. It seems to happed when "Touch Bar shows" is set to "Expanded Control Strip"

**Comment by juneoh** [comment]
Happens for me too when using control strip. There’s an x button at the left that puts pock into this weird state; and there’s a pock icon in the control strip which does nothing. Perhaps something with the recent macOS update?

![08D1CFB6-B17F-4118-AF65-7F8F551B4686](https://user-images.githubusercontent.com/18067322/74084500-1af3ad00-4ab3-11ea-9e46-4abbed9d430d.jpeg)

**Comment by danseely** [comment]
I've been having the same issue as @delfuego, and I just realized it may be due to user error (at least for me). I hadn't noticed the note in the preferences, under the `Hide Control Strip` checkbox. It says "Double press `⌃ Control` key to toggle between Pock and System Touch Bar." I've confirmed for myself, throughout these last 2 days, that when I notice Pock disappearing, I can tap Control twice and it comes back.

I think it's entirely possible that I've been inadvertently hitting this feature and not realizing it by occasionally double-tapping Control. I'm going to keep an eye on it, and I'll report back, but I'd recommend to anyone else having the same issue to give it a try.

**Comment by delfuego** [comment]
@danseely HOLY CRAP, that's probably exactly what's happening for me too! Sigh.

**Comment by angristan** [comment]
It's probably what has been happening to me too... Thanks!

**Comment by danseely** [comment]
@delfuego assuming you're able to test & confirm, I'm sure the maintainer here would appreciate this being closed 😉

**Comment by angristan** [comment]
Considering how many users upvoted this, it might be worth updating the default shortcut?

**Comment by danseely** [comment]
Agreed, gp. And/or: 

- adding more clear documentation about the feature
- adding a specific setting for it, instead of coupling it with the `hide control strip` settin
  - ^ turning that setting `off` by default

**Comment by diegosucaria** [comment]
It happens to me too. After returning from sleep, the original touch bar displays.
If I disable the control strip totally, it works fine...   but I can't do that bc I really like how the control strip works for volume and brightness
