### ISSUE TITLE
Pock 0.8.1-5 crashing at least once a day in Big Sur

### ISSUE THREAD

**Issue by huynhxloi** [pock/pock#474]
**Describe the bug**
Pock 0.8.1-5 crashing at least once a day in Big Sur. Probably will try downgrading if this continues, it's getting pretty ridiculous.

**How to reproduce**

Intermittent, see the attached logs below. 

**Crashlog**
See the attached. 
[Process: Pock [765].txt](https://github.com/pock/pock/files/6411765/Process.Pock.765.txt)
[Process: Pock [653].txt](https://github.com/pock/pock/files/6411766/Process.Pock.653.txt)

**Versions:**
 - macOS version: 11.3
 - Pock version:  0.8.1-5

**Comment by robmoffat** [comment]
Same version, same issue - creating a comment to watch

**Comment by Standaa** [comment]
Crashing several times a day on my end. Real pity because it is the only tool that makes the TB useful.

**Comment by Standaa** [comment]
Duplicate of https://github.com/pock/pock/issues/454#issuecomment-821913911

**Comment by Jseeca** [comment]
Yes same behaviour with mine. Although for me it only occurs after a dock it. It's annoying because everytime I unplug my Mac I have to manually open pock to keep it running again. For some reason is also disables the default control strip after it runs so when it does crash there is no way to adjust the brightness/volumes without reopening pock. At this point it's either I uninstall pock or I stick with the default Touch Bar. As I need a reliable way to control brightness/volume. 

Really hope they patch this issue because there are similar posts too and it's been at least a month with no update. It's somewhat unusable in the current state. Just commenting to keep watch.

**Comment by Standaa** [comment]
@Jseeca There is a fix proposed in the linked issue above (https://github.com/pock/pock/issues/454#issuecomment-821913911).
It has been working flawlessly ever since I applied it.

**Comment by moeffju** [comment]
Still happens in 0.9. The "fix" linked is a workaround that restarts it without addressing the underlying issue.

**Comment by psu1989** [comment]
Love the app, but would really like to see a fix for the constant crashing.

**Comment by ALenfant** [comment]
It's crashing like 10x/day now, this makes it completely unusable unfortunately... :/
