### ISSUE TITLE
Long press on Control Center widget doesn't show slider anymore

### ISSUE THREAD

**Issue by bradydjohnson** [pock/pock#509]
On Pock 0.9.0-22, long pressing or sliding on the control center widget does't invoke sliders like it used to.

**Comment by Knogobert** [comment]
I quite like this feature/bug though, as I think the slider is annoying UX. Perhaps it should be under a settings flag?

**Comment by glli** [comment]
Invoking sliders is very annoying, I love the current setting. If there is a setting for the item spacing like Dock widget, it would be perfect.

**Comment by Nornode** [comment]
I miss this too! 

Previously you could have just "Show Brigness Items" ticked (one, ticked item of Brightness items and one icon showed up) and I could click it to invoke a slider. I don't need the up and down items to save taskbar realestate.
Now I have to have either Brightness Down or Up ticked to control it, and it can't invoke a slider and it takes op way more space.

If I would be able to choose: please enable the "top" level Brightness item in order to use the slider, and if any of the below (Up or down) is ticked, you can't invoke the slider on the up and down items, only on the main brightness item.

Obviously, I miss and would hope that the same should apply to the volume Items.
