### ISSUE TITLE
Wanting to contribute to the project and create a quick Touch Bar widget to command q (quit) an active running application

### ISSUE THREAD

**Issue by kylegorter** [pock/pock#555]
Hi guys, im new to Swift macOS and id love to contribute to this project. Im sure many people as well as myself would like to easily quit an app with a press of a Touch Bar button. Ive created a few simple iOS apps and games a few years ago but im wanting to further my experience with macOS. I want to learn and would love if some professionals can guide and help me make something out of myself and show people and potential businesses my accomplishments in app development.

**Describe the feature you'd like to have in Pock**
So Pock already has the widget that shows running apps on the Touch Bar and I thought that if there was a button on the far left that can quit an active running application showing on the menu bar. For example, if Safari is running and Safari showing menu tabs in the menu bar(active window), I can just press a button titled "Quit" on the Touch Bar and it entirely quit the application without needing to press the command + q combination or dragging the mouse and selecting Quit in the menu bar.

Ive set up a template and dropped it onto my Touch Bar already but now im in limbo looking on stack exchange for some answers to see if its possible and how.

 Im open to all suggestions and helpful guides for my learning career.

**Comment by kylegorter** [comment]
Alright so ive figured it out and its actually working. Ummm does anyone want the widget?

**Comment by bluerxing** [comment]
> Alright so ive figured it out and its actually working. Ummm does anyone want the widget?
> 
> @pigigaldi How should I go about editing the repo? https://github.com/kylegorter/Quit-Pock

That's a great job, Thanks, I am a user of pock, I also have this demand. I put quit button on the side of button esc. Could I put a request about adding the mouse click function like esc widget. you know, users tend to click esc or quit or app icon when their hands are on the mouse rather than leave the mouse and use the finger to press(Maybe i am just the one who is so lazy, lol)
also, I am not good at Swift but I am wondering how to add a function that when mouse point hover twice on the button of the screen, the mac default touch bar can switch to Pock' toubar. because this a bug or macos setting that the macos default touch bar always unexpectedly override the Pock' toubar. I am thinking if there is something like hovering twice for hidden-dock showing. could i get some idea from you benefit from your expert knowledge.
