### ISSUE TITLE
Difference between "Workflow with Control Strip" vs "Spaces" vs "App," etc.

### ISSUE THREAD

**Issue by bradydjohnson** [pock/pock#560]
Less an issue, more a documentation request:

What is the difference between all of these options?
<img width="251" alt="image" src="https://user-images.githubusercontent.com/6741590/154189870-0aded105-2de6-4763-adf0-df62b5df9aaa.png">

**Comment by diff3** [comment]
I've been searching for an 3 party app for touchbar which can switch between different layout by using shortcuts and Pock came close to what I was looking for. 

I would love to switch between, "Pock" App Controls, "Stock" App controls and "Stock" Extended control strip depend on situation or app I'm using. Most of the time I'm using extended control strip, but in some app I have configure shortcuts to "Stock" App controls and it's a pain to go to settings/keyboard and switch. 

But otherwise a greate app!

**Comment by KushinP** [comment]
I completely agree with @diff3 there needs to be a way to sitch between stock controls and Pock.
