### ISSUE TITLE
Constant activity on the network

### ISSUE THREAD

**Issue by HighPriest** [pock/pock#589]
**Describe the bug**
Pock is constantly sending kB of data over the wire, according to built-in "Activity Monitor" application

**How to reproduce**
```
1. Launch Pock
2. Disable Update checking and all widgets
3. Open Network view in Activity Monitor
4. See that Pock is still sending data over Network connection
```

**Screenshots**
<img width="958" alt="Screenshot 2022-06-26 at 16 07 47" src="https://user-images.githubusercontent.com/58490197/175818172-7092a7cb-23ed-439a-98bb-c9fd173b50ab.png">

**Expected behaviour**
The app should not need to send any data, but it does, even when blocked with built-in Firewall.

**Versions:**
 - macOS version: 12.4
 - Pock version:  0.9.0-20

**Comment by pigigaldi** [comment]
That’s normal. Pock send some analytics data to AppCenter in order to keep track of issues and overall performance.

**Comment by HighPriest** [comment]
This is not _"normal"_. I have not agreed anywhere for performance and application status tracking.

I am on a metered network in a foreign country, I cannot afford to use my connection for sending anything, if I don't state explicitly that there is an issue with the application.

There HAS TO BE an opt-out option. And opt-in by default is a malicious practice: https://www.interaction-design.org/literature/topics/automatic-opt-in

**Comment by pigigaldi** [comment]
I got your point, and I'll add an opt-out mechanism to allow users to decide if they want to help me improve performance by giving explicit consent on the first install of the app and through the Preference pane. 

Sadly, I don't know when I'll have the time to work on this, though. I usually put my hands on these projects in my spare time, since they are not meant to be commercial packages (that's why they are free and open-source), and unfortunately I had zero-spare time in the latest months.

In the meanwhile, feel free to uninstall the app while you're on a metered connection to avoid any issues. I'll add a statement in the README of this repo to let other users know about this situation. Thanks again for pointing it out.
 
To answer your latest questions, the Dock widget, in particular, sends some events to let me better investigate why some bugs/glitches happen. You can keep track of these events by opening the console log (`Advanced -> Show debug console…`) and filtering for `[Pock][Analytics]` to see which events are sent. All events are anonymous and only contain a label and a little set of properties (like app or widget version or some event-specific indicator).
For the Firewall, I don't know how it is configured. The only thing I can say is that nothing special is done inside Pock to elude that kind of restriction since there's no reason for me to do that.

**Comment by HighPriest** [comment]
I am sorry @pigigaldi , but what were you trying to accomplish, by closing a ticket with "Yes, I will do something about it"?
This is a jarring topic, which EVERYONE that is going to try to use your software, should know about!

No new mentions in the readme, no additions to an installer. But the ticket is now hidden...
Avoidance is not a solution, Luigi. Please re-open the ticket.
