### ISSUE TITLE
Pock exits after waking up MacBook

### ISSUE THREAD

**Issue by iDjay** [pock/pock#98]
Steps to reproduce:
1. put MacBook into sleep mode while Pock runs in the background.
2. wake MacBook up from sleep mode -> Pock doesn‘t run anymore in the background.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by pigigaldi** [comment]
Does it crash or it just disappears from the Touch Bar?

**Comment by iDjay** [comment]
>Does it crash or it just disappears from the Touch Bar?

@pigigaldi it quits, no crash log appears but the app doesn’t run anymore...

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by stevezhengshiqi** [comment]
I have the same problem on 10.15. My version is 0.6.1 and it crashes once a day or two.
I got this in `Console.app`:
`Oct  9 21:45:16 Steves-MacBook-Pro com.apple.xpc.launchd[1] (com.pigigaldi.pock.23088[727]): Service exited due to SIGSEGV | sent by exc handler[727]`

And here's is full crash report if @pigigaldi is needed.
[Crash Report.txt](https://github.com/pigigaldi/Pock/files/3710195/Crash.Report.txt)

Thank you for this great app!

**Comment by pigigaldi** [comment]
Please @stevezhengshiqi update to 0.6.2 and let me know if this issue still occurs.

**Comment by stevezhengshiqi** [comment]
@pigigaldi The 0.6.2 and 0.6.3 work so well and I barely get panic.
However, I did get a panic report a few days ago.
[Panic Report.txt](https://github.com/pigigaldi/Pock/files/3900777/Panic.Report.txt)

**Comment by stevezhengshiqi** [comment]
Here's another one.
[Pock_2019-12-01-215750_Steves-MacBook-Pro.crash.zip](https://github.com/pigigaldi/Pock/files/3913860/Pock_2019-12-01-215750_Steves-MacBook-Pro.crash.zip)

**Comment by stevezhengshiqi** [comment]
@pigigaldi Thank you so much for maintaining this project. It's pretty stable now. By the way, I got another crash log if you need. The error messages I sent in this issue are all `EXC_BAD_ACCESS (SIGSEGV)`

[Pock_2020-02-17-222925_Steves-MacBook-Pro.crash.zip](https://github.com/pigigaldi/Pock/files/4221582/Pock_2020-02-17-222925_Steves-MacBook-Pro.crash.zip)
